[package]
name = "basket-cli"
version = "1.1.0"
edition = "2021"

[[bin]]
name = "basket"
path = "src/main.rs"

[dependencies]
basket = { path = "../basket", features = ["json"] }
clap = { version = "4", features = ["derive"] }
serde_json = "1"
