name: docs

on:
  push:
    paths:
      - '**.tape'
      - '**.yml'
      - '**.rs'

jobs:
  vhs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build
      - name: add basket to PATH
        run: echo "$(pwd)/target/debug" >> $GITHUB_PATH

      - uses: charmbracelet/vhs-action@v1
        with:
          path: 'docs/cli.tape'
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "vhs: update generated vhs gif"
          branch: main
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: '*.gif'
